
import image1 from '@/assests/image (18).png';
import image2 from '@/assests/image (19).png';
import image3 from '@/assests/image (20).png';
import image4 from '@/assests/image (21).png';
import image5 from '@/assests/image (22).png';
import image6 from '@/assests/image (23).png';
import image7 from '@/assests/image (24).png';
export const Products = [
    {
        id: 1,
        image: image1,
        category: "Flowers",
        brand: "Nature's Bliss",
        description: "Organic and aromatic flowers for relaxation.",
        rating: 4.8,
        price: 25.99,
        discountPrice: 19.99,
        title: "Nature's Bliss Flowers",
    },
    {
        id: 2,
        image: image2,
        category: "Edibles",
        brand: "Sweet Delights",
        description: "Delicious cannabis-infused chocolates.",
        rating: 4.5,
        price: 15.99,
        discountPrice: 12.99,
        title: "Sweet Delights Edibles",
    },
    {
        id: 3,
        image: image3,
        category: "Concentrates",
        brand: "Pure Extracts",
        description: "High-potency cannabis concentrates.",
        rating: 4.9,
        price: 40.0,
        discountPrice: 35.0,
        title: "Pure Extracts Concentrates",
    },
    {
        id: 4,
        image: image4,
        category: "Pre-Rolls",
        brand: "Roll It Up",
        description: "Perfectly rolled joints for convenience.",
        rating: 4.2,
        price: 10.99,
        discountPrice: 0,
        title: "Roll It Up Pre-Rolls",
    },
    {
        id: 5,
        image: image5,
        category: "Vapes",
        brand: "Cloud Nine",
        description: "Smooth and flavorful vaping experience.",
        rating: 4.6,
        price: 29.99,
        discountPrice: 25.99,
        title: "Cloud Nine Vapes",
    },
    {
        id: 6,
        image: image5,
        category: "Flowers",
        brand: "Bloom Valley",
        description: "Fresh flowers with soothing effects.",
        rating: 4.7,
        price: 28.99,
        discountPrice: 22.99,
        title: "Bloom Valley Flowers",
    },
    {
        id: 7,
        image: image6,
        category: "Edibles",
        brand: "Tasty Bites",
        description: "Soft gummies with natural flavors.",
        rating: 4.3,
        price: 18.99,
        discountPrice: 0,
        title: "Tasty Bites Edibles",
    },
    {
        id: 8,
        image: image7,
        category: "Concentrates",
        brand: "Golden Drops",
        description: "Rich and refined cannabis oil.",
        rating: 4.9,
        price: 42.0,
        discountPrice: 37.0,
        title: "Golden Drops Concentrates",
    },
    {
        id: 9,
        image: image1,
        category: "Pre-Rolls",
        brand: "Quick Puff",
        description: "Compact and ready-to-use joints.",
        rating: 4.1,
        price: 12.99,
        discountPrice: 9.99,
        title: "Quick Puff Pre-Rolls",
    },
    {
        id: 10,
        image: image2,
        category: "Vapes",
        brand: "VaporEase",
        description: "Stylish and portable vape pens.",
        rating: 4.5,
        price: 31.99,
        discountPrice: 0,
        title: "VaporEase Vapes",
    },
    {
        id: 11,
        image: image3,
        category: "Flowers",
        brand: "Eden Greens",
        description: "Hand-picked flowers for the purest experience.",
        rating: 4.8,
        price: 24.99,
        discountPrice: 19.99,
        title: "Eden Greens Flowers",
    },
    {
        id: 12,
        image: image4,
        category: "Edibles",
        brand: "Chewy Bliss",
        description: "Satisfy your sweet tooth with infused cookies.",
        rating: 4.6,
        price: 20.99,
        discountPrice: 0,
        title: "Chewy Bliss Edibles",
    },
    {
        id: 13,
        image: image5,
        category: "Concentrates",
        brand: "Crystal Pure",
        description: "Shatter with unmatched potency.",
        rating: 4.9,
        price: 50.0,
        discountPrice: 45.0,
        title: "Crystal Pure Concentrates",
    },
    {
        id: 14,
        image: image6,
        category: "Pre-Rolls",
        brand: "Easy Roll",
        description: "Light and enjoy, no preparation needed.",
        rating: 4.3,
        price: 11.99,
        discountPrice: 0,
        title: "Easy Roll Pre-Rolls",
    },
    {
        id: 15,
        image: image7,
        category: "Vapes",
        brand: "AirStream",
        description: "Effortless and smooth vapor delivery.",
        rating: 4.7,
        price: 33.99,
        discountPrice: 29.99,
        title: "AirStream Vapes",
    },
    {
        id: 16,
        image: image7,
        category: "Flowers",
        brand: "Floral Essence",
        description: "Pure flowers with an intense aroma.",
        rating: 4.5,
        price: 27.99,
        discountPrice: 0,
        title: "Floral Essence Flowers",
    },
    {
        id: 17,
        image: image1,
        category: "Edibles",
        brand: "Candy Treats",
        description: "Delightful candies infused with cannabis.",
        rating: 4.2,
        price: 16.99,
        discountPrice: 13.99,
        title: "Candy Treats Edibles",
    },
    {
        id: 18,
        image: image2,
        category: "Concentrates",
        brand: "Extract King",
        description: "Highly potent extracts for connoisseurs.",
        rating: 4.9,
        price: 55.0,
        discountPrice: 50.0,
        title: "Extract King Concentrates",
    },
    {
        id: 19,
        image: image2,
        category: "Pre-Rolls",
        brand: "Swift Roll",
        description: "Convenient and high-quality pre-rolls.",
        rating: 4.3,
        price: 13.99,
        discountPrice: 0,
        title: "Swift Roll Pre-Rolls",
    },
    {
        id: 20,
        image: image3,
        category: "Vapes",
        brand: "VapePro",
        description: "Top-notch vaping devices.",
        rating: 4.8,
        price: 36.99,
        discountPrice: 32.99,
        title: "VapePro Vapes",
    },
    {
        id: 21,
        image: image4,
        category: "Flowers",
        brand: "Garden Bliss",
        description: "Experience the freshness of our flowers.",
        rating: 4.6,
        price: 29.99,
        discountPrice: 24.99,
        title: "Garden Bliss Flowers",
    },
    {
        id: 22,
        image: image5,
        category: "Edibles",
        brand: "Brownie Heaven",
        description: "Mouthwatering brownies with a twist.",
        rating: 4.4,
        price: 22.99,
        discountPrice: 18.99,
        title: "Brownie Heaven Edibles",
    },
    {
        id: 23,
        image: image6,
        category: "Concentrates",
        brand: "Liquid Gold",
        description: "Pure and rich cannabis concentrates.",
        rating: 4.7,
        price: 48.0,
        discountPrice: 0,
        title: "Liquid Gold Concentrates",
    },
    {
        id: 24,
        image: image7,
        category: "Pre-Rolls",
        brand: "Leaf Roll",
        description: "Crafted pre-rolls for ultimate satisfaction.",
        rating: 4.2,
        price: 12.49,
        discountPrice: 9.99,
        title: "Leaf Roll Pre-Rolls",
    },
    {
        id: 25,
        image: image1,
        category: "Vapes",
        brand: "EasyVape",
        description: "Simple and smooth vaping solutions.",
        rating: 4.5,
        price: 28.99,
        discountPrice: 24.99,
        title: "EasyVape Vapes",
    },
    {
        id: 26,
        image: image2,
        category: "Flowers",
        brand: "Tranquil Blooms",
        description: "Relax with our premium flower selection.",
        rating: 4.9,
        price: 26.99,
        discountPrice: 0,
        title: "Tranquil Blooms Flowers",
    },
    {
        id: 27,
        image: image3,
        category: "Edibles",
        brand: "Cookie Crunch",
        description: "Irresistible cookies infused with goodness.",
        rating: 4.3,
        price: 17.99,
        discountPrice: 14.49,
        title: "Cookie Crunch Edibles",
    },
    {
        id: 28,
        image: image4,
        category: "Concentrates",
        brand: "Pure Crystal",
        description: "The purest form of cannabis concentrates.",
        rating: 4.8,
        price: 45.0,
        discountPrice: 0,
        title: "Pure Crystal Concentrates",
    },
    {
        id: 29,
        image: image5,
        category: "Pre-Rolls",
        brand: "Roll Master",
        description: "High-quality and ready-to-use pre-rolls.",
        rating: 4.1,
        price: 14.99,
        discountPrice: 11.99,
        title: "Roll Master Pre-Rolls",
    },
    {
        id: 30,
        image: image6,
        category: "Vapes",
        brand: "VapeLux",
        description: "Luxurious vaping experience.",
        rating: 4.6,
        price: 34.99,
        discountPrice: 29.99,
        title: "VapeLux Vapes",
    },
    {
        id: 31,
        image: image7,
        category: "Flowers",
        brand: "Harmony Blooms",
        description: "Flowers that bring harmony and peace.",
        rating: 4.8,
        price: 30.99,
        discountPrice: 0,
        title: "Harmony Blooms Flowers",
    },
    {
        id: 32,
        image: image1,
        category: "Edibles",
        brand: "Fudge Delight",
        description: "Rich fudge infused with premium cannabis.",
        rating: 4.7,
        price: 21.99,
        discountPrice: 18.49,
        title: "Fudge Delight Edibles",
    },
    {
        id: 33,
        image: image2,
        category: "Concentrates",
        brand: "Ultra Extracts",
        description: "Next-level potency for enthusiasts.",
        rating: 4.9,
        price: 60.0,
        discountPrice: 55.0,
        title: "Ultra Extracts Concentrates",
    },
    {
        id: 34,
        image: image3,
        category: "Pre-Rolls",
        brand: "Quick Light",
        description: "Fast and easy pre-rolls for busy days.",
        rating: 4.4,
        price: 10.99,
        discountPrice: 8.49,
        title: "Quick Light Pre-Rolls",
    },
    {
        id: 35,
        image: image7,
        category: "Vapes",
        brand: "Smooth Vapor",
        description: "Smooth and consistent vaping.",
        rating: 4.7,
        price: 37.99,
        discountPrice: 0,
        title: "Smooth Vapor Vapes",
    },
];

